"""Preset analytical insights (Task B3).

Three curated analyses. Each one runs a fixed, trusted aggregation in Python and
then asks the LLM only to narrate the numbers it is handed.

The aggregations are deliberately not generated by the model. These are the
headline insights shown on the dashboard's Overview tab, so they must be correct
every time; letting a 4B model write the code for them would make the front page
of the app a coin flip. The model's job here is narration, which is what it is
reliably good at.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable

import pandas as pd

from src.config import DATA, LLM
from src.data.query import aggregate
from src.llm.client import LLMClient, LLMError

NARRATIVE_SYSTEM_PROMPT = """You are a retail analytics consultant writing for an
executive audience.

You are given the title of an analysis and its computed results. Write a concise
Markdown briefing.

RULES:
- Every number you cite must appear in the data given to you. Never invent one.
- Structure: a bold one-line headline, then 3-4 bullet points, then a single
  sentence of recommended action.
- Say what the numbers mean commercially, not what the table contains.
- Format currency as $1,234 and rates as percentages.
- No preamble, no restating the question, no describing your process.
"""


@dataclass
class Insight:
    """One preset analysis: its computed tables plus the LLM's narration."""

    key: str
    title: str
    description: str
    tables: dict[str, pd.DataFrame] = field(default_factory=dict)
    narrative: str = ""
    elapsed_seconds: float = 0.0
    error: str | None = None


# --------------------------------------------------------------------- 1/3
def _overview(df: pd.DataFrame) -> dict[str, pd.DataFrame]:
    """Dataset Overview: summary statistics, distributions, top/bottom N."""
    totals = aggregate(
        df,
        group_by=[],
        metrics={
            "Sales": ["sum", "mean"],
            "Profit": ["sum", "mean"],
            "Quantity": ["sum"],
            "Discount": ["mean"],
            "Order ID": ["count"],
        },
    ).data
    totals["Profit_margin_pct"] = round(
        100 * totals["Profit_sum"].iloc[0] / totals["Sales_sum"].iloc[0], 2
    )

    by_category = aggregate(
        df,
        group_by=["Category"],
        metrics={"Sales": ["sum"], "Profit": ["sum"]},
        sort_by="Sales_sum",
    ).data

    top_subcats = aggregate(
        df,
        group_by=["Sub-Category"],
        metrics={"Profit": ["sum"]},
        sort_by="Profit_sum",
        limit=5,
    ).data

    bottom_subcats = aggregate(
        df,
        group_by=["Sub-Category"],
        metrics={"Profit": ["sum"]},
        sort_by="Profit_sum",
        ascending=True,
        limit=5,
    ).data

    return {
        "Headline totals": totals,
        "Performance by category": by_category,
        "Top 5 sub-categories by profit": top_subcats,
        "Bottom 5 sub-categories by profit": bottom_subcats,
    }


# --------------------------------------------------------------------- 2/3
def _trend(df: pd.DataFrame) -> dict[str, pd.DataFrame]:
    """Trend and comparison analysis: temporal plus categorical."""
    yearly = aggregate(
        df,
        group_by=["Order Year"],
        metrics={"Sales": ["sum"], "Profit": ["sum"], "Order ID": ["count"]},
        sort_by="Order Year",
        ascending=True,
    ).data
    yearly["Sales_growth_pct"] = (yearly["Sales_sum"].pct_change() * 100).round(1)
    yearly["Margin_pct"] = (100 * yearly["Profit_sum"] / yearly["Sales_sum"]).round(2)

    by_region_year = (
        df.pivot_table(
            index="Region",
            columns="Order Year",
            values="Sales",
            aggfunc="sum",
            observed=True,
        )
        .round(0)
        .reset_index()
    )

    by_segment = aggregate(
        df,
        group_by=["Segment"],
        metrics={"Sales": ["sum"], "Profit": ["sum"], "Order ID": ["count"]},
        sort_by="Sales_sum",
    ).data
    by_segment["Margin_pct"] = (
        100 * by_segment["Profit_sum"] / by_segment["Sales_sum"]
    ).round(2)

    return {
        "Year-on-year performance": yearly,
        "Sales by region and year": by_region_year,
        "Customer segment comparison": by_segment,
    }


# --------------------------------------------------------------------- 3/3
def _anomalies(df: pd.DataFrame) -> dict[str, pd.DataFrame]:
    """Anomaly and outlier report: IQR outliers plus structural loss-makers."""
    profit = df["Profit"]
    q1, q3 = profit.quantile(0.25), profit.quantile(0.75)
    iqr = q3 - q1
    low = q1 - DATA.iqr_multiplier * iqr
    high = q3 + DATA.iqr_multiplier * iqr

    extreme_losses = (
        df[df["Profit"] < low][
            ["Order ID", "Sub-Category", "Sales", "Discount", "Profit"]
        ]
        .nsmallest(5, "Profit")
        .reset_index(drop=True)
    )

    # Sub-categories that lose money on average are a structural pricing
    # problem, not a run of unlucky orders. That distinction is the insight.
    unprofitable = aggregate(
        df,
        group_by=["Sub-Category"],
        metrics={"Profit": ["sum", "mean"], "Discount": ["mean"], "Order ID": ["count"]},
        sort_by="Profit_sum",
        ascending=True,
        limit=5,
    ).data

    # The mechanism: margin collapses as discount deepens.
    discount_bands = df.assign(
        band=pd.cut(
            df["Discount"],
            bins=[-0.01, 0.0, 0.2, 0.4, 0.6, 1.0],
            labels=["0%", "1-20%", "21-40%", "41-60%", "61%+"],
        )
    )
    by_band = (
        discount_bands.groupby("band", observed=True)
        .agg(
            lines=("Profit", "size"),
            total_profit=("Profit", "sum"),
            mean_profit=("Profit", "mean"),
            mean_sales=("Sales", "mean"),
        )
        .round(2)
        .reset_index()
    )

    summary = pd.DataFrame(
        [
            {
                "iqr_outlier_threshold_low": round(low, 2),
                "iqr_outlier_threshold_high": round(high, 2),
                "loss_making_lines": int((df["Profit"] < 0).sum()),
                "loss_making_pct": round(100 * (df["Profit"] < 0).mean(), 1),
                "total_losses": round(df.loc[df["Profit"] < 0, "Profit"].sum(), 2),
            }
        ]
    )

    return {
        "Anomaly summary": summary,
        "Profit by discount band": by_band,
        "Structurally unprofitable sub-categories": unprofitable,
        "Five worst individual line items": extreme_losses,
    }


PRESETS: dict[str, tuple[str, str, Callable[[pd.DataFrame], dict[str, pd.DataFrame]]]] = {
    "overview": (
        "Dataset Overview",
        "Headline totals, category performance, and the best and worst sub-categories.",
        _overview,
    ),
    "trend": (
        "Trend & Comparison Analysis",
        "Year-on-year growth, regional trajectories, and customer segment comparison.",
        _trend,
    ),
    "anomaly": (
        "Anomaly & Outlier Report",
        "IQR outliers, structural loss-makers, and the discount-margin mechanism.",
        _anomalies,
    ),
}


def _tables_to_prompt(tables: dict[str, pd.DataFrame]) -> str:
    blocks = []
    for name, frame in tables.items():
        blocks.append(f"### {name}\n{frame.to_string(index=False)}")
    return "\n\n".join(blocks)


def generate_insight(
    key: str, df: pd.DataFrame, client: LLMClient | None = None
) -> Insight:
    """Run one preset analysis and narrate it.

    Args:
        key: One of the keys in PRESETS.
        df: The (optionally filtered) dataset.
        client: LLM client; constructed if not supplied.

    Returns:
        An Insight carrying the computed tables and the Markdown narrative. If
        the LLM call fails, the tables are still returned and `error` is set, so
        the UI degrades to showing correct numbers without commentary rather
        than showing nothing.
    """
    if key not in PRESETS:
        raise KeyError(f"Unknown insight {key!r}. Available: {list(PRESETS)}")

    title, description, compute = PRESETS[key]
    tables = compute(df)

    insight = Insight(key=key, title=title, description=description, tables=tables)

    client = client or LLMClient()
    messages = [
        {"role": "system", "content": NARRATIVE_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                f"ANALYSIS: {title}\n"
                f"SCOPE: {len(df):,} order line items.\n\n"
                f"{_tables_to_prompt(tables)}\n\n"
                "Write the briefing."
            ),
        },
    ]

    try:
        response = client.complete(
            messages,
            temperature=LLM.narrative_temperature,
            max_tokens=800,
        )
        insight.narrative = response.text
        insight.elapsed_seconds = response.elapsed_seconds
        if response.truncated:
            insight.narrative += "\n\n*(Response was cut off at the token limit.)*"
    except LLMError as exc:
        insight.error = str(exc)
        insight.narrative = (
            f"*(Narrative unavailable: {exc}. The computed figures below are "
            "still correct.)*"
        )

    return insight
